### ISSUE TITLE
Restarting from scratch

### ISSUE THREAD

**Issue by jchidley** [WardCunningham/wiki-plugin-morseteacher#2]
Some feedback on the web version vs and PC one.  I had been using the PC version with it's start from scratch method.  Then I started using the web based one.

With both, I knew I was done learning because I became overwhelmed: my recognition of the earlier letters started to fail.  With the PC version, I could just take a break restart it and begin again, it was a helpful way to revise what I had already learnt.  In this way, I was able to progress slightly further with a session later in the day.

With the web one, there doesn't seem a way of restarting from scratch, therefore no way to revise what I had already learnt.  I also worry that I will be starting off from the same point where I was overwhelmed before.

All in all, I feel like the PC one, with it's start from scratch method, is a better way to learn.

**Comment by WardCunningham** [comment]
Thank you for reporting this experience.

Years ago I would argue that "start from scratch" with each session was desirable for the very reason you explain. It was also all that could be easily programmed so the the position was self-serving too.

With this version I explored the idea of practicing code as if it were editing a document. If you type tab or otherwise leave practice your progress so far is saved as markup within the morseteacher. Each time you tab a new revision is stored. In this example the page edges turn yellow showing that the page has been edited.

![image](https://user-images.githubusercontent.com/12127/38425146-e73c28e2-3967-11e8-8f9a-45ba523e7b8f.png)

You can recall any earlier version by clicking on that version in the journal. This is not explained in the morseteacher because it is just part of the way federated wiki always works.

See http://fed.wiki.org/how-to-wiki.html, especially How To Read History.
